// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package service

import (
	"github.com/naftulikay/golang-webapp/pkg/dao"
	"github.com/naftulikay/golang-webapp/pkg/database"
	"github.com/naftulikay/golang-webapp/pkg/interfaces"
	"github.com/naftulikay/golang-webapp/pkg/service"
	"github.com/naftulikay/golang-webapp/pkg/types"
)

// Injectors from injectors.go:

func initializeLoginService(config interfaces.MySQLConfig, jwtKey types.JWTKey, loginServiceLogger types.LoginServiceLogger, jwtServiceLogger types.JWTServiceLogger, userDaoLogger types.UserDaoLogger, databaseLogger types.DatabaseLogger) (interfaces.LoginService, error) {
	db, err := database.Connect(config, databaseLogger)
	if err != nil {
		return nil, err
	}
	userDaoImpl := dao.NewUserDao(db, userDaoLogger)
	jwtServiceImpl, err := service.NewJWTService(jwtKey, jwtServiceLogger)
	if err != nil {
		return nil, err
	}
	loginServiceImpl := service.NewLoginService(userDaoImpl, jwtServiceImpl, loginServiceLogger)
	return loginServiceImpl, nil
}
