---
# NOTE unfortunately github actions does _not_ support yaml anchors, so we have a lot of duplicate code
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

env:
  CACHE_VERSION: v1
  GO_VERSION: '1.16'
  GOLANG_CACHE_NAME: golang

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.GOLANG_CACHE_NAME }}-${{ env.CACHE_VERSION }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-${{ env.GOLANG_CACHE_NAME }}-${{ env.CACHE_VERSION }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/swag
      - run: go get -u github.com/swaggo/swag/cmd/swag
      - run: go mod download -x
      # FIXME enable swag model generation: "swag init"
      - run: go build -v

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.GOLANG_CACHE_NAME }}-${{ env.CACHE_VERSION }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-${{ env.GOLANG_CACHE_NAME }}-${{ env.CACHE_VERSION }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/swag
      - run: go get -u github.com/swaggo/swag/cmd/swag
      # FIXME enable swag model generation: "swag init"
      - run: go mod download -x
      - run: go test -v ./...

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        env:
          GO111MODULE: on
        with:
          # NOTE add -no-fail to skip
          args: -color ./...