---
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch: {}

env:
  CACHE_VERSION: v1
  DOCKER_CACHE_NAME: docker

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.DOCKER_CACHE_NAME }}-app-${{ env.CACHE_VERSION }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-${{ env.DOCKER_CACHE_NAME }}-app-${{ env.CACHE_VERSION }}
          path: /tmp/.buildx-cache
      - uses: docker/setup-buildx-action@v1
      # NOTE add docker/login-action@v1 to push to a registry
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |-
            naftulikay/golang-web-app:latest
            naftulikay/golang-web-app:edge

  database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.DOCKER_CACHE_NAME }}-app-${{ env.CACHE_VERSION }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-${{ env.DOCKER_CACHE_NAME }}-app-${{ env.CACHE_VERSION }}
          path: /tmp/.buildx-cache
      - uses: docker/setup-buildx-action@v1
      # NOTE add docker/login-action@v1 to push to a registry
      - uses: docker/build-push-action@v2
        with:
          context: docker/images/database
          push: false
          tags: |-
            naftulikay/golang-web-app-db:latest
            naftulikay/golang-web-app-db:edge