---
# NOTE unfortunately github actions does _not_ support yaml anchors, so we have a lot of duplicate code
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

env:
  CACHE_VERSION: v1
  GO_VERSION: '1.16'
  GOLANG_CACHE_NAME: golang

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.GOLANG_CACHE_NAME }}-${{ env.CACHE_VERSION }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-${{ env.GOLANG_CACHE_NAME }}-${{ env.CACHE_VERSION }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/swag
            ~/go/bin/wire
      - run: make install-tools
      - run: make download
      - run: make generate
      - run: go build -v
      - uses: actions/upload-artifact@v2
        with:
          name: codegen
          path: |
            **/wire_gen.go
            docs/docs.go
            docs/swagger.json
            docs/swagger.yaml
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.GOLANG_CACHE_NAME }}-${{ env.CACHE_VERSION }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-${{ env.GOLANG_CACHE_NAME }}-${{ env.CACHE_VERSION }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/swag
            ~/go/bin/wire
      - run: make install-tools
      - run: make download
      - run: make generate
      - run: go test -v ./...

  audit:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: codegen
      - uses: securego/gosec@master
        env:
          GO111MODULE: on
        with:
          # NOTE add -no-fail to skip
          args: -color ./...